Ronaldo/blog/urls.py
from django.urls import path
from .views import index, single

urlpatterns = [
    path('', index, name='index'),
    path('single/<int:pk>/', single, name='single'),
]

Ronaldo/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ronaldo/blog/models.py
from django.db import models


# Create your models here.

class Home(models.Model):
    name = models.CharField(max_length=202)

    last_update = models.DateTimeField(auto_now=True)
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class About(models.Model):
    title = models.CharField(max_length=202)
    image = models.ImageField()
    text = models.TextField()
    name = models.CharField(max_length=202)
    birth = models.CharField(max_length=202)
    address = models.CharField(max_length=202)
    code = models.CharField(max_length=202)
    email = models.EmailField()
    phone = models.CharField(max_length=202)
    project = models.IntegerField()

    last_update = models.DateTimeField(auto_now=True)
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Sponsor(models.Model):
    title = models.CharField(max_length=202)
    image = models.ImageField()

    def __str__(self):
        return self.title


class Service(models.Model):
    icon = models.CharField(max_length=202)
    title = models.CharField(max_length=202)
    text = models.CharField(max_length=400)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Project(models.Model):
    title = models.CharField(max_length=202)
    text = models.CharField(max_length=202)
    image = models.ImageField()

    last_update = models.DateTimeField(auto_now=True)
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=202)


    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=202)

    def __str__(self):
        return self.title

class Blog(models.Model):
    category = models.ForeignKey("Category", on_delete=models.CASCADE)
    tags = models.ManyToManyField("Tag")
    image = models.ImageField()
    title = models.CharField(max_length=202)
    text = models.CharField(max_length=303)
    content = models.TextField(null=True, blank=True)
    content_continued = models.TextField(null=True, blank=True)
    creative = models.TextField(null=True, blank=True)

    last_update = models.DateTimeField(auto_now=True)
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-id"]



class Contactme(models.Model):
    title = models.CharField(max_length=202)
    icon = models.CharField(max_length=202)
    text = models.CharField(max_length=303)

    def __str__(self):
        return self.title

Ronaldo/contact/models.py
from django.db import models


# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=202)
    email = models.EmailField()
    subject = models.CharField(max_length=303)
    text = models.TextField()

    # created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

Ronaldo/resume/models.py
from django.db import models


# Create your models here.


class Education(models.Model):
    title = models.CharField(max_length=202)
    start_finish = models.CharField(max_length=202)
    address = models.CharField(max_length=303)
    text = models.CharField(max_length=505)

    def __str__(self):
        return self.title


class Experience(models.Model):
    title = models.CharField(max_length=202)
    start_finish = models.CharField(max_length=202)
    address = models.CharField(max_length=303)
    text = models.CharField(max_length=505)

    def __str__(self):
        return self.title


class Skill_one(models.Model):
    title = models.CharField(max_length=202, null=True, blank=True)
    percentage = models.IntegerField(null=True, blank=True)
    last_week = models.IntegerField(null=True, blank=True)
    last_month = models.IntegerField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Skill_two(models.Model):
    name = models.CharField(max_length=202, null=True, blank=True)
    foiz = models.IntegerField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Awards(models.Model):
    title = models.CharField(max_length=202)
    start_finish = models.CharField(max_length=202)
    address = models.CharField(max_length=303)
    text = models.CharField(max_length=505)

    def __str__(self):
        return self.title

Ronaldo/contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field_name.capitalize()

Ronaldo/blog/views.py
from django.shortcuts import render, redirect
from .models import About, Home, Project, Blog, Service, Contactme, Sponsor, Category, Tag
from resume.models import Education, Experience, Awards, Skill_two, Skill_one
from comment.forms import CommentForm
from contact.forms import ContactForm
from comment.models import Comment


# Create your views here.


def index(request):
    object_home = Home.objects.all()
    object_sponsor = Sponsor.objects.all()
    object_awards = Awards.objects.all()
    object_education = Education.objects.all()
    object_experience = Experience.objects.all()
    object_skillone = Skill_one.objects.all()
    object_skilltwo = Skill_two.objects.all()
    object_about = About.objects.all()
    object_project = Project.objects.all()
    object_blog = Blog.objects.all()[:3]
    object_service = Service.objects.all()
    object_contactme = Contactme.objects.all()
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("/#contact-section")

    context = {
        'homes': object_home,
        'edus': object_education,
        'sponsors': object_sponsor,
        'exps': object_experience,
        'awas': object_awards,
        'skillones': object_skillone,
        'skilltwos': object_skilltwo,
        'abouts': object_about,
        'projects': object_project,
        'services': object_service,
        'contactmes': object_contactme,
        'blogs': object_blog,
        'form': form,
    }

    return render(request, 'index.html', context)


def single(request, pk):
    object_blogs = Blog.objects.all()[:3]
    object_service = Service.objects.all()
    object_category = Category.objects.all()
    object_tag = Tag.objects.all()
    object_contactme = Contactme.objects.all()
    object_blog = Blog.objects.get(id=pk)
    form = CommentForm(request.POST or None)
    # object_comment = Comment.objects.all()
    url = request.META.get("HTTP_REFERER")
    if form.is_valid():
        var = form.save(commit=False)
        var.blog = object_blog
        var.save()
        return redirect(url)
    context = {
        'form': form,
        'blogs': object_blog,
        'categorys': object_category,
        'tags': object_tag,
        # 'comments': object_comment,
        'contactmes': object_contactme,
        'services': object_service,
        'recents': object_blogs,
    }

    return render(request, 'single.html', context)

Ronaldo/contact/views.py
from django.shortcuts import render

# Create your views here.

Ronaldo/resume/views.py
from django.shortcuts import render

# Create your views here.

Ronaldo/templates/about.html
{% load static %}
<section class="ftco-about img ftco-section ftco-no-pt ftco-no-pb" id="about-section">
    <div class="container">
        <div class="row d-flex no-gutters">
            {% for about in abouts %}
            <div class="col-md-6 col-lg-6 d-flex">
                <div class="img-about img d-flex align-items-stretch">
                    <div class="overlay"></div>
                    <div class="img d-flex align-self-stretch align-items-center"
                         style="background-image:url({{ about.image.url }});">
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-6 pl-md-5 py-5">
                <div class="row justify-content-start pb-3">
                    <div class="col-md-12 heading-section ftco-animate">
                        <h1 class="big">About</h1>
                        <h2 class="mb-4">About Me</h2>
                        <p>{{ about.text }}</p>
                        <ul class="about-info mt-4 px-md-0 px-2">
                            <li class="d-flex"><span>Name:</span> <span>{{ about.name }}</span></li>
                            <li class="d-flex"><span>Date of birth:</span> <span>{{ about.birth }}</span></li>
                            <li class="d-flex"><span>Address:</span> <span>{{ about.address }}</span></li>
                            <li class="d-flex"><span>Zip code:</span> <span>{{ about.code }}</span></li>
                            <li class="d-flex"><span>Email:</span> <span><a
                                    href="https://preview.colorlib.com/cdn-cgi/l/email-protection" class="__cf_email__"
                                    data-cfemail="f0829f9e919c949fb0979d91999cde939f9d">{{ about.email }}</a></span>
                            </li>
                            <li class="d-flex"><span>Phone: </span> <span>{{ about.phone }}</span></li>
                        </ul>
                    </div>
                </div>
                <div class="counter-wrap ftco-animate d-flex mt-md-3">
                    <div class="text">
                        <p class="mb-4">
                            <span class="number" data-number="{{ about.project }}">0</span>
                            <span>Project complete</span>
                        </p>
                        <p><a href="#contact-section" class="btn btn-primary py-3 px-3">Contact</a></p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<section class="ftco-section ftco-partner">
    <div class="container">
        <div class="row">
            {% for sponsor in sponsors %}
            <div class="col-sm ftco-animate">
                <a href="#" class="partner"><img src="{{ sponsor.image.url }}" class="img-fluid"
                                                 alt="Colorlib Template"></a>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

Ronaldo/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<!-- Mirrored from preview.colorlib.com/theme/ronaldo/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 05 Nov 2022 15:01:52 GMT -->
<head>
    <title>Ronaldo - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet"
          href="{% static 'css/A.open-iconic-bootstrap.min.css+animate.css+owl.carousel.min.css+owl.theme.default.min.css+magnific-popup.css+aos.css+ionicons.min.css+flaticon.css+icomoon.css+style.css,Mcc.03G1SaxbUZ.css' %}"/>
    <script nonce="5b296fc7-0edf-4338-b790-ac83b1238c15">
        (function(w,d){!function(Z,_,ba,bb){Z.zarazData=Z.zarazData||{};Z.zarazData.executed=[];Z.zaraz={deferred:[],listeners:[]};Z.zaraz.q=[];Z.zaraz._f=function(bc){return function(){var bd=Array.prototype.slice.call(arguments);Z.zaraz.q.push({m:bc,a:bd})}};for(const be of["track","set","debug"])Z.zaraz[be]=Z.zaraz._f(be);Z.zaraz.init=()=>{var bf=_.getElementsByTagName(bb)[0],bg=_.createElement(bb),bh=_.getElementsByTagName("title")[0];bh&&(Z.zarazData.t=_.getElementsByTagName("title")[0].text);Z.zarazData.x=Math.random();Z.zarazData.w=Z.screen.width;Z.zarazData.h=Z.screen.height;Z.zarazData.j=Z.innerHeight;Z.zarazData.e=Z.innerWidth;Z.zarazData.l=Z.location.href;Z.zarazData.r=_.referrer;Z.zarazData.k=Z.screen.colorDepth;Z.zarazData.n=_.characterSet;Z.zarazData.o=(new Date).getTimezoneOffset();Z.zarazData.q=[];for(;Z.zaraz.q.length;){const bl=Z.zaraz.q.shift();Z.zarazData.q.push(bl)}bg.defer=!0;for(const bm of[localStorage,sessionStorage])Object.keys(bm||{}).filter((bo=>bo.startsWith("_zaraz_"))).forEach((bn=>{try{Z.zarazData["z_"+bn.slice(7)]=JSON.parse(bm.getItem(bn))}catch{Z.zarazData["z_"+bn.slice(7)]=bm.getItem(bn)}}));bg.referrerPolicy="origin";bg.src="https://preview.colorlib.com/cdn-cgi/zaraz/s.js?z="+btoa(encodeURIComponent(JSON.stringify(Z.zarazData)));bf.parentNode.insertBefore(bg,bf)};["complete","interactive"].includes(_.readyState)?zaraz.init():Z.addEventListener("DOMContentLoaded",zaraz.init)}(w,d,0,"script");})(window,document);
    </script>
</head>
<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
{% block content %}

{% endblock %}
<footer class="ftco-footer ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">About</h2>
                    {% for about in abouts %}
                    <p>{{ about.text}}</p>
                    {% endfor %}
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href=""><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="https://www.facebook.com/profile.php?id=100087969003073"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="https://www.instagram.com/abdumalikovich_rustam/"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-4">
                    <h2 class="ftco-heading-2">Links</h2>
                    <ul class="list-unstyled">
                        <li><a href="#home-section"><span class="icon-long-arrow-right mr-2"></span>Home</a></li>
                        <li><a href="#about-section"><span class="icon-long-arrow-right mr-2"></span>About</a></li>
                        <li><a href="#services-section"><span class="icon-long-arrow-right mr-2"></span>Services</a></li>
                        <li><a href="#projects-section"><span class="icon-long-arrow-right mr-2"></span>Projects</a></li>
                        <li><a href="#contact-section"><span class="icon-long-arrow-right mr-2"></span>Contact</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Services</h2>
                    <ul class="list-unstyled">
                        {% for service in services %}
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>{{ service.title}}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    {% for contactme in contactmes %}
                    <div class="block-23 mb-3">
                        <ul>
                            <li>{{ contactme.title }} <br> {{ contactme.text }} </li>
                        </ul>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <p>Abdumalikovich Rustamjon Isroilov</p>
            </div>
        </div>
    </div>
</footer>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js+popper.min.js+bootstrap.min.js.pagespeed.jc.bMyveoHKiv.js' %}"></script>
<script>eval(mod_pagespeed_gb7yraQys5);</script>
<script>eval(mod_pagespeed_RGKn6SW32g);</script>
<script>eval(mod_pagespeed_h9rX52Z4Ti);</script>
<script src="{% static 'js/jquery.easing.1.3.js+jquery.waypoints.min.js+jquery.stellar.min.js+owl.carousel.min.js.pagespeed.jc.P2hE5bOhqO.js' %}"></script>
<script>eval(mod_pagespeed_rBeIzFEDC0);</script>
<script>eval(mod_pagespeed_m_l$l00rWq);</script>
<script>eval(mod_pagespeed_tOGOF_KHft);</script>
<script>eval(mod_pagespeed_g921z9MGXC);</script>
<script src="{% static 'js/jquery.magnific-popup.min.js+aos.js+jquery.animateNumber.min.js+scrollax.min.js+main.js.pagespeed.jc.GTDEZB3xMJ.js' %}"></script>
<script>eval(mod_pagespeed_P9B3uJNt60);</script>
<script>eval(mod_pagespeed_ACE0ce7fTR);</script>
<script>eval(mod_pagespeed_awRnuKerVJ);</script>
<script>eval(mod_pagespeed_iVOyfib5U4);</script>
<script>eval(mod_pagespeed_udwuFYXF0f);</script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');

</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993"
        integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA=="
        data-cf-beacon='{"rayId":"7656779a4bf6d95b","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2022.11.0","si":100}'
        crossorigin="anonymous"></script>
</body>

<!-- Mirrored from preview.colorlib.com/theme/ronaldo/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 05 Nov 2022 15:02:16 GMT -->
</html>

Ronaldo/templates/blog.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
<script nonce="52b6f9e4-61cd-455b-8e4c-4c231e4ab420">(function(w,d){!function(Z,_,ba,bb){Z.zarazData=Z.zarazData||{};Z.zarazData.executed=[];Z.zaraz={deferred:[],listeners:[]};Z.zaraz.q=[];Z.zaraz._f=function(bc){return function(){var bd=Array.prototype.slice.call(arguments);Z.zaraz.q.push({m:bc,a:bd})}};for(const be of["track","set","debug"])Z.zaraz[be]=Z.zaraz._f(be);Z.zaraz.init=()=>{var bf=_.getElementsByTagName(bb)[0],bg=_.createElement(bb),bh=_.getElementsByTagName("title")[0];bh&&(Z.zarazData.t=_.getElementsByTagName("title")[0].text);Z.zarazData.x=Math.random();Z.zarazData.w=Z.screen.width;Z.zarazData.h=Z.screen.height;Z.zarazData.j=Z.innerHeight;Z.zarazData.e=Z.innerWidth;Z.zarazData.l=Z.location.href;Z.zarazData.r=_.referrer;Z.zarazData.k=Z.screen.colorDepth;Z.zarazData.n=_.characterSet;Z.zarazData.o=(new Date).getTimezoneOffset();Z.zarazData.q=[];for(;Z.zaraz.q.length;){const bl=Z.zaraz.q.shift();Z.zarazData.q.push(bl)}bg.defer=!0;for(const bm of[localStorage,sessionStorage])Object.keys(bm||{}).filter((bo=>bo.startsWith("_zaraz_"))).forEach((bn=>{try{Z.zarazData["z_"+bn.slice(7)]=JSON.parse(bm.getItem(bn))}catch{Z.zarazData["z_"+bn.slice(7)]=bm.getItem(bn)}}));bg.referrerPolicy="origin";bg.src="/cdn-cgi/zaraz/s.js?z="+btoa(encodeURIComponent(JSON.stringify(Z.zarazData)));bf.parentNode.insertBefore(bg,bf)};["complete","interactive"].includes(_.readyState)?zaraz.init():Z.addEventListener("DOMContentLoaded",zaraz.init)}(w,d,0,"script");})(window,document);</script></head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.41 (Ubuntu) Server at preview.colorlib.com Port 443</address>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data-cf-beacon='{"rayId":"765678de4edcdf68","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2022.11.0","si":100}' crossorigin="anonymous"></script>
</body></html>

Ronaldo/templates/single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar ftco-navbar-light site-navbar-target" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="index-2.html"><span>R</span>onaldo</a>
        <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse"
                data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav nav ml-auto">
                <li class="nav-item"><a href="#home-section" class="nav-link"><span>Home</span></a></li>
                <li class="nav-item"><a href="#about-section" class="nav-link"><span>About</span></a></li>
                <li class="nav-item"><a href="#resume-section" class="nav-link"><span>Resume</span></a></li>
                <li class="nav-item"><a href="#services-section" class="nav-link"><span>Services</span></a>
                </li>
                <li class="nav-item"><a href="#projects-section" class="nav-link"><span>Projects</span></a>
                </li>
                <li class="nav-item"><a href="#blog-section" class="nav-link"><span>My Blog</span></a></li>
                <li class="nav-item"><a href="#contact-section" class="nav-link"><span>Contact</span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="hero-wrap js-fullheight">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight justify-content-center align-items-center">
            <div class="col-lg-10 ftco-animate d-flex align-items-center">
                <div class="text text-center">
                    <h1 class="mb-3 bread">Blog Single Post</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="/">Home <i
                            class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="/#blog-section">Blog <i
                            class="ion-ios-arrow-forward"></i></a></span> <span>Blog Single <i
                            class="ion-ios-arrow-forward"></i></span></p>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 ftco-animate">
                <h2 class="mb-3">It is a long established fact a reader be distracted</h2>
                <p>{{ blogs.content }}</p>
                <p>
                    <img src="{{ blogs.image.url }}" alt="" class="img-fluid">
                </p>
                <p>{{ blogs.content_continued }}</p>
                <h2 class="mb-3 mt-5">#2. Creative WordPress Themes</h2>
                <p>{{ blogs.creative }}</p>
                <div class="pt-5 mt-5">
                    <h3 class="mb-5">{{ blogs.comments.all.count }} Comments</h3>
                    <ul class="comment-list">
                        {% for comment in blogs.comments.all %}
                        <li class="comment">
                            <div class="vcard bio">
                                <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>{{ comment.name }}</h3>
                                <div class="meta">Sept. 12, 2019 at 2:21pm</div>
                                <p>{{ comment.message}}</p>
                                <p><a href="#" class="reply">Reply</a></p>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Leave a comment</h3>
                        <form method="post" action="#" class="p-5 bg-light">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.name }}
                            </div>
                            <div class="form-group">
                                {{ form.email }}
                            </div>
                            <div class="form-group">
                                {{ form.website }}
                            </div>
                            <div class="form-group">
                                {{ form.message }}
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 sidebar ftco-animate">
                <div class="sidebar-box">
                    <form action="#" class="search-form">
                        <div class="form-group">
                            <span class="icon icon-search"></span>
                            <input type="text" class="form-control" placeholder="Search...">
                        </div>
                    </form>
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3 class="heading-sidebar">Categories</h3>
                    <ul class="categories">
                        {% for category in categorys %}
                        <li><a href="#">{{ category.title}} <span>({{ category.blog_set.all.count }})</span></a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3 class="heading-sidebar">Recent Blog</h3>
                    {% for recent in recents %}
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({{ recent.image.url }});"></a>
                        <div class="text">
                            <h3 class="heading"><a href="#">{{ recent.title }}</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span> March 12, 2019</a></div>
                                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3 class="heading-sidebar">Tag Cloud</h3>
                    <div class="tagcloud">
                        {% for tag in tags %}
                        <a href="#" class="tag-cloud-link">{{ tag.title }}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3 class="heading-sidebar">Paragraph</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus
                        voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur
                        similique, inventore eos fugit cupiditate numquam!</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}